"""Public integration catalogue and connection capability metadata."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Integration:
    key: str
    name: str
    category: str
    markets: tuple[str, ...]
    status: str
    logo: str
    logo_alt: str
    description: str
    capabilities: tuple[str, ...]
    direction: str
    ownership: str
    docs_url: str


CATALOGUE = (
    Integration(
        key="file_import",
        name="Employee file import",
        category="HR software",
        markets=("UK", "EE"),
        status="Adapter ready",
        logo="/static/integrations/file-import.svg",
        logo_alt="Employee file import icon",
        description="Import employee master records from a CSV or TSV export of any payroll or HR system.",
        capabilities=("CSV/Excel export import", "Employee master records"),
        direction="Import · uploaded files",
        ownership="Uploaded export remains source",
        docs_url="https://github.com/predictivelabsai/FastAccounts/blob/main/docs/product_roadmap.md#22-universal-file-import-2026-10-09",
    ),
    Integration(
        key="quickbooks",
        name="QuickBooks Online",
        category="Accounting platform",
        markets=("UK",),
        status="Adapter ready · not connected",
        logo="/static/integrations/quickbooks.svg",
        logo_alt="QuickBooks logo",
        description="Coexist with an existing QuickBooks company through reviewed imports and controlled exports.",
        capabilities=("Contacts", "Invoices and bills", "Payments", "Accounts and tax", "Attachments"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.intuit.com/app/developer/qbo/docs/learn/explore-the-quickbooks-online-api",
    ),
    Integration(
        key="xero",
        name="Xero",
        category="Accounting platform",
        markets=("UK", "EE"),
        status="Adapter ready · not connected",
        logo="/static/integrations/xero.svg",
        logo_alt="Xero logo",
        description="Exchange accounting data with a Xero organisation using tenant-scoped OAuth and explicit conflict review.",
        capabilities=("Contacts", "Invoices and credit notes", "Payments", "Bank transactions", "Reports"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.xero.com/documentation/api/accounting/overview",
    ),
    Integration(
        key="merit",
        name="Merit Aktiva",
        category="Accounting platform",
        markets=("EE",),
        status="Adapter ready · test company needed",
        logo="/static/integrations/merit-aktiva.svg",
        logo_alt="Merit Aktiva logo",
        description="Support Estonian accountant workflows with HMAC-signed V2 invoice, payment, tax, GL and report exchange.",
        capabilities=("Sales and purchase invoices", "Payments", "Tax IDs", "GL transactions", "Dimensions"),
        direction="Import and export · reviewed",
        ownership="Configured per object",
        docs_url="https://api.merit.ee/connecting-robots/reference-manual/",
    ),
    Integration(
        key="hmrc",
        name="HMRC Making Tax Digital",
        category="Filing agent",
        markets=("UK",),
        status="Sandbox adapter · filing gated",
        logo="/static/integrations/hmrc.svg",
        logo_alt="HMRC service mark",
        description="Prepare accountant-reviewed VAT workpapers now; add sandbox obligations and submission flows before production approval.",
        capabilities=("VAT obligations", "Nine-box workpaper", "Review declaration", "Submission receipt plan"),
        direction="FastAccounts to HMRC",
        ownership="Accountant-approved filing",
        docs_url="https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0",
    ),
    Integration(
        key="emta",
        name="Estonian Tax and Customs Board",
        category="Filing agent",
        markets=("EE",),
        status="Export ready · filing gated",
        logo="/static/integrations/emta.svg",
        logo_alt="Estonian Tax and Customs Board service mark",
        description="Generate accountant-reviewed KMD and VD workpapers and retain a stub for a future supported filing channel.",
        capabilities=("KMD workpaper", "VD preparation", "Audit export", "Direct filing discovery"),
        direction="FastAccounts to accountant",
        ownership="Accountant-reviewed export",
        docs_url="https://www.emta.ee/en/business-client/taxes-and-payment/value-added-tax",
    ),
    Integration(
        key="open_banking",
        name="Open banking",
        category="Bank data",
        markets=("UK", "EE"),
        status="Read-only candidate",
        logo="/static/integrations/open-banking.svg",
        logo_alt="Open banking icon",
        description="Read booked transactions through a selected AISP after GB/EE business-bank coverage and legal review.",
        capabilities=("Consent lifecycle", "Accounts and balances", "Booked transactions", "Reconciliation input"),
        direction="Read-only first",
        ownership="Bank remains source",
        docs_url="https://standards.openbanking.org.uk/api-specifications/latest/",
    ),
    Integration(
        key="fasthr",
        name="FastHR",
        category="HR software",
        markets=("EE", "Global"),
        status="Adapter ready",
        logo="/static/integrations/fasthr.svg",
        logo_alt="FastHR placeholder mark",
        description="FastHR employee master records imported for bureau payroll.",
        capabilities=("Employee master records", "Employment status", "Base salary", "Organisation details"),
        direction="Import · employee master data",
        ownership="FastHR remains source",
        docs_url="https://fasthr.eu/docs",
    ),
    Integration(
        key="bamboohr",
        name="BambooHR",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/bamboohr.svg",
        logo_alt="BambooHR placeholder mark",
        description="Use BambooHR employee data as a reviewed source for bureau-payroll setup and inputs.",
        capabilities=("Employee master records", "Employee portal notes", "Time off", "Org chart", "Documents"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://documentation.bamboohr.com/",
    ),
    Integration(
        key="personio",
        name="Personio",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/personio.svg",
        logo_alt="Personio placeholder mark",
        description="Use the European HR suite as a reviewed source of employee and payroll-input data for bureau payroll.",
        capabilities=("Employee records", "Attendance", "Absences", "Documents", "Payroll inputs"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.personio.de/",
    ),
    Integration(
        key="hibob",
        name="Bob (HiBob)",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/hibob.svg",
        logo_alt="Bob by HiBob placeholder mark",
        description="Bring selected Bob workforce data into a reviewed bureau-payroll intake.",
        capabilities=("Employee directory", "Employee lifecycle", "Time management"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://apidocs.hibob.com/",
    ),
    Integration(
        key="zoho_people",
        name="Zoho People",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/zoho_people.svg",
        logo_alt="Zoho People placeholder mark",
        description="Use Zoho People records and working-time data as reviewed payroll inputs.",
        capabilities=("Employee records", "Attendance", "Leave", "Timesheets", "Forms"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://www.zoho.com/people/api/v3/overview.html",
    ),
    Integration(
        key="employment_hero",
        name="Employment Hero",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/employment_hero.svg",
        logo_alt="Employment Hero placeholder mark",
        description="Stage selected Employment Hero workforce data for review before it enters bureau payroll.",
        capabilities=("Employee records", "Onboarding", "Leave", "Timesheets", "Payroll inputs"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.employmenthero.com/",
    ),
    Integration(
        key="workday",
        name="Workday",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/workday.svg",
        logo_alt="Workday placeholder mark",
        description="Treat enterprise HCM worker and payroll-input data as a reviewed source for bureau payroll.",
        capabilities=("Worker records", "Organisation structures", "Time and absence", "Compensation", "Payroll inputs"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.workday.com/documentation",
    ),
    Integration(
        key="hrmaster",
        name="HRmaster (HR Master)",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/hrmaster.svg",
        logo_alt="HRmaster placeholder mark",
        description="Use the Hungarian HR suite as a reviewed source for employee records and payroll inputs.",
        capabilities=("Personnel records", "Payroll inputs", "Recruitment", "Evaluations", "Cafeteria benefits"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://www.hrmaster.hu/",
    ),
    Integration(
        key="gusto",
        name="Gusto",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/gusto.svg",
        logo_alt="Gusto placeholder mark",
        description="Use the US payroll platform as a reviewed source where a client group includes a US entity.",
        capabilities=("Employee records", "Payroll inputs", "Time off", "Benefits data", "Contractor records"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://docs.gusto.com/",
    ),
    Integration(
        key="rippling",
        name="Rippling",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/rippling.svg",
        logo_alt="Rippling placeholder mark",
        description="Bring selected workforce records into a reviewed payroll intake for client books.",
        capabilities=("Employee records", "Onboarding", "Time and attendance", "Leave", "Payroll inputs"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.rippling.com/",
    ),
    Integration(
        key="deel",
        name="Deel",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/deel.svg",
        logo_alt="Deel placeholder mark",
        description="Use global payroll and employer-of-record data as reviewed inputs for bureau payroll.",
        capabilities=("Worker records", "Contracts", "Global payroll inputs", "Time off", "Expenses"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://developer.deel.com/",
    ),
    Integration(
        key="odoo_hr",
        name="Odoo HR",
        category="HR software",
        markets=("UK", "EE"),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/odoo_hr.svg",
        logo_alt="Odoo HR placeholder mark",
        description="Configure each tenant with its Odoo URL and database name for reviewed imports over XML-RPC or JSON-RPC.",
        capabilities=("Employee records", "Attendance", "Time off", "Recruitment", "Expenses"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://www.odoo.com/documentation/19.0/developer/reference/external_rpc_api.html",
    ),
    Integration(
        key="persona_fujitsu",
        name="Fujitsu Persona",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/persona_fujitsu.svg",
        logo_alt="Fujitsu Persona placeholder mark",
        description="Estonia's oldest personnel and payroll software has served organisations since 1995. Its modules can supply reviewed employee and payroll inputs.",
        capabilities=("Personnel records", "Payroll", "Working time", "Self-service portal"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://persona.ee/",
    ),
    Integration(
        key="wemply",
        name="Wemply",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/wemply.svg",
        logo_alt="Wemply placeholder mark",
        description="A modular staffing, working-time and Estonian payroll platform used by more than 1,000 companies. Wemply was named Aasta HR lahendus 2025.",
        capabilities=("Staffing", "Working time", "Estonian payroll", "TSD reporting", "TÖR reporting"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://wemply.com/",
    ),
    Integration(
        key="hours24",
        name="hours24",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/hours24.svg",
        logo_alt="hours24 placeholder mark",
        description="AI-assisted time tracking and scheduling used in Estonia and Finland. A free tier supports up to five employees.",
        capabilities=("AI-assisted time capture", "Working-time records", "Work schedules"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://hours24.com/",
    ),
    Integration(
        key="yester",
        name="Yester",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/yester.svg",
        logo_alt="Yester placeholder mark",
        description="An Estonian workforce platform operating since 2000, with onboarding, expenses, travel and driving logs. It is tightly integrated with Merit Tarkvara.",
        capabilities=("Onboarding", "Expense reports", "Business travel", "Driving logs", "Merit integration"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://yester.eu/",
    ),
    Integration(
        key="hrm4baltics",
        name="HRM4Baltics (Digmatix)",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/hrm4baltics.svg",
        logo_alt="HRM4Baltics placeholder mark",
        description="A Microsoft Dynamics 365 Business Central HRM solution covering Estonian, Latvian and Lithuanian payroll. It includes X-tee integration.",
        capabilities=("Personnel records", "Estonian payroll", "Latvian payroll", "Lithuanian payroll", "X-tee integration"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://digmatix.com/",
    ),
    Integration(
        key="merit_palk",
        name="Merit Palk",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/merit_palk.svg",
        logo_alt="Merit Palk placeholder mark",
        description="Estonia's most-used payroll software serves more than 25,000 firms and offers a free tier for up to two employees. It can pair with the existing Merit Aktiva accounting adapter.",
        capabilities=("Employee records", "Payroll calculations", "Payslips", "TSD preparation", "Merit Aktiva pairing"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://www.merit.ee/",
    ),
    Integration(
        key="taavi_palk",
        name="Taavi Palk",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/taavi_palk.svg",
        logo_alt="Taavi Palk placeholder mark",
        description="An Estonian payroll product used by more than 1,500 companies. It prepares statutory reports and exports payslips to Estonian bookkeeping systems.",
        capabilities=("TSD reports", "Register reports", "Statistics reports", "Payslip exports"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://taavi.ee/",
    ),
    Integration(
        key="andevis",
        name="Andevis",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/andevis.svg",
        logo_alt="Andevis placeholder mark",
        description="A customisable Estonian HR suite whose modules can provide reviewed personnel and payroll inputs.",
        capabilities=("Personnel records", "Working time", "Payroll", "Training", "Development reviews"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://andevis.ee/",
    ),
    Integration(
        key="eeva",
        name="Eeva (Eetasoft)",
        category="HR software",
        markets=("EE",),
        status="Roadmap · no adapter yet",
        logo="/static/integrations/eeva.svg",
        logo_alt="Eeva by Eetasoft placeholder mark",
        description="Eeva's personnel module manages core employment records and is linked to Eeva payroll. Data would enter bureau payroll only through reviewed imports.",
        capabilities=("Contracts", "Orders", "Leave", "ISCO classifier", "Eeva payroll link"),
        direction="Import first · export by policy",
        ownership="Configured per object",
        docs_url="https://eetasoft.ee/",
    ),
)


def get_integration(key: str) -> Integration | None:
    return next((item for item in CATALOGUE if item.key == key), None)
